### ISSUE TITLE
翻译进度追踪

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/learnlatex.github.io#3]
## 说明

- [x] 已完成
- [ ] 未完成
- :runner: 已被人认领 / 正在翻译
- :thinking: 内容和数量需要进一步讨论

欢迎大家认领、完善翻译以及参与讨论～

## 核心课程（`lesson-xx`）

- [x] 1 - LaTeX 是什么？它如何工作？
- [x] 2 - 让 LaTeX 跑起来
- [x] 3 - LaTeX 文档基础结构 @KevinZonda - #8
- [x] 4 - 逻辑结构 @LogCreative - #9
- [x] 5 - 使用文档类来切换设计 @LogCreative - #10
- [x] 6 - 使用宏包和定义来扩展 LaTeX @LogCreative - #11
- [x] 7 - 插图与定位 @LogCreative - #11
- [x] 8 - 表格 @LogCreative - #11
- [x] 9 - 交叉引用 @muyuuuu - #2
- [x] 10 - 数学公式 @LogCreative - #12
- [x] 11 - 格式：字体与间距 @LogCreative - #12
- [x] 12 - 引用与参考文献 @LogCreative - #12
- [x] 13 - 组建更长的文档 @LogCreative - #14
- [x] 14 - 字体与 Unicode 引擎 @LogCreative - #14
- [x] 15 - 处理错误 @LogCreative - #14
- [x] 16 - 查看说明文档并获取帮助 @RungeCC - #5

## 延伸阅读（`more-xx`）

- [x] 1 - 更多：LaTeX 是什么？它如何工作？ @LogCreative - #15
- [x] 2 - 更多：让 LaTeX 跑起来 @LogCreative - #15
- [x] 3 - 更多：LaTeX 文档基础结构 @LogCreative - #15
- [x] 4 - 更多：逻辑结构 @LogCreative - #15
- [x] 5 - 更多：使用文档类来切换设计 @LogCreative - #15
- [x] 6 - 更多：使用宏包和定义来扩展 LaTeX @LogCreative - #15
- [x] 7 - 更多：插图与定位 @LogCreative - #15
- [x] 8 - 更多：表格 @LogCreative - #15
- [x] 9 - 更多：交叉引用 @LogCreative - #15
- [x] 10 - 更多：数学公式 @LogCreative - #16
- [x] 11 - 更多：格式：字体与间距 @LogCreative - #16
- [x] 12 - 更多：引用与参考文献 @LogCreative - #16
- [x] 13 - 更多：组建更长的文档 @LogCreative - #16
- [x] 14 - 更多：字体与 Unicode 引擎 @LogCreative - #16
- [x] 15 - 更多：处理错误 @LogCreative - #16
- [x] 16 - 更多：查看说明文档并获取帮助 @LogCreative - #16

## 额外教程

- [x] `extra-01`: LaTeX 案例展示 @LogCreative - #17
- [x] `language-01`: 排版中文

## 杂项

- [x] `index`
- [x] `mission`
- [x] `help`
- [x] `contact`
- [x] `licenses`

**Comment by muyuuuu** [comment]
你忘记 @自己 了

**Comment by stone-zeng** [comment]
> 你忘记 @自己 了

故意的【机智】

**Comment by KevinZonda** [comment]
@stone-zeng Hi，我希望帮助中文的翻译，但是我发现目前分支落后于主分支。例如在英文版中 lesson3 为 Basic LaTeX document structure ，但是中文分支为 Your first LaTeX document (Chinese)

所有我建议暂时先同步上游

**Comment by stone-zeng** [comment]
标题我调整了一下，但实际上的翻译并没有怎么动，所以其他东西暂时先不同步了

**Comment by stone-zeng** [comment]
感谢各位的帮助（especially @LogCreative）！

现在整个教程都已翻译完成，之后会做一些校对与打磨，然后尽快合并进上游分支。
